"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
import numpy
n=1
n1=0
p=0
sum=0
while True:
    n
    if n>4000000:
        break
    if n%2==0:
        sum=sum+n
    p=n
    n=n+n1
    n1=p
print(sum)
print(n)